name: CI

on: push

jobs:
  list:
    uses: jill64/reusable-workflow/.github/workflows/lint.yml@main
  build-adapter:
    uses: jill64/reusable-workflow/.github/workflows/build.yml@main
    with:
      build-command: pnpm build:adapter
  check:
    uses: jill64/reusable-workflow/.github/workflows/check.yml@main
